### ISSUE TITLE
Under DataDog spanlist kgateway shows with the same level/as peer with the downstream service

### ISSUE THREAD

**Issue by binoysankar** [kgateway-dev/kgateway#11636]
### kgateway version

v2.1.0-main

### Kubernetes Version

1.30.5

### Describe the bug

Hi,

I have implemented [OpenTelemetry Access Log and Tracing Support](https://github.com/kgateway-dev/kgateway/pull/11396) in my AKS cluster and it is working fine but with a small issue.

I am having AKS cluster with kgateway and the traces are send to DataDog backend using datadog cluster agents. In DataDog its showing the spans in the same level as that of my microservice. Ideally the spanlist should not be showing as siblings but under kgateway.
I have also set the property `spawnUpstreamSpan` as true.
If you see the attached screenshot marked in green, both are showing in the same level. Actually it should be under kgateway span.

<img width="705" height="335" alt="Image" src="https://github.com/user-attachments/assets/0bb21aa6-086a-443e-a30b-49c6dc2cfa46" />

<img width="705" height="206" alt="Image" src="https://github.com/user-attachments/assets/4483ef67-7b91-4586-9786-22f035ddc6f9" />

### Expected Behavior

Expected behaviour should be that the downstream microservice(s) should be shown under kgateway and not at the same/peer level.

### Steps to reproduce the bug

`helm upgrade -i --create-namespace --namespace kgateway-system --version v2.1.0-main kgateway-crds oci://cr.kgateway.dev/kgateway-dev/charts/kgateway-crds`

`helm upgrade -i -n kgateway-system kgateway oci://cr.kgateway.dev/kgateway-dev/charts/kgateway \
--version v2.1.0-main`

> kubectl apply -f - <<EOF
> apiVersion: gateway.kgateway.dev/v1alpha1
> kind: HTTPListenerPolicy
> metadata:
>   name: tracing-policy
>   namespace: kgateway-system
> spec:
>   targetRefs:
>   - group: gateway.networking.k8s.io
>     kind: Gateway
>     name: abc-gateway
>   tracing:
>     provider:
>       openTelemetry:
>         serviceName: "abc-kgateway"
>         resourceDetectors:
>           - environmentResourceDetector: {}
>         grpcService:
>           authority: "opentelemetry-collector.kgateway-system.svc.cluster.local:4317"
>           backendRef:
>             name: opentelemetry-collector
>             namespace: kgateway-system
>             port: 4317
>     spawnUpstreamSpan: true
>     attributes:
>       - name: "env"
>         literal:
>           value: "dev"
> EOF

**Comment by binoysankar** [comment]
I am also facing another issue as below. This didn't happen first time btw.
I can confirm this issue is not there when using the latest release version `v2.0.3`

`[2025-07-11 08:19:58.604][1][error][config] [external/envoy/source/common/listener_manager/listener_manager_impl.cc:1241] listener 'listener~443' failed to bind or apply socket options: cannot bind '[::]:443': Permission denied 
`

What i observed is the kgateway service is using the targetPort as 443 instead of 8443

> apiVersion: v1
> kind: Service
> metadata:
>   creationTimestamp: "2025-07-11T08:47:00Z"
>   finalizers:
>   - service.kubernetes.io/load-balancer-cleanup
>   labels:
>     app.kubernetes.io/instance: abc-gateway
>     app.kubernetes.io/managed-by: Helm
>     app.kubernetes.io/name: abc-gateway
>     app.kubernetes.io/version: v2.1.0-main
>     gateway.networking.k8s.io/gateway-name: abc-gateway
>     helm.sh/chart: kgateway-proxy-v2.1.0-main
>     kgateway: kube-gateway
>   name: abc-gateway
>   namespace: kgateway-system
>   ownerReferences:
>   - apiVersion: gateway.networking.k8s.io/v1
>     controller: true
>     kind: Gateway
>     name: abc-gateway
>     uid: 2892dc3c-758f-4231-bc2e-276f03d51642
>   resourceVersion: "289588897"
>   uid: 52edb81b-7709-4048-b35e-c7f79d6be139
> spec:
>   allocateLoadBalancerNodePorts: true
>   clusterIP: 10.0.184.198
>   clusterIPs:
>   - 10.0.184.198
>   externalTrafficPolicy: Cluster
>   internalTrafficPolicy: Cluster
>   ipFamilies:
>   - IPv4
>   ipFamilyPolicy: SingleStack
>   ports:
>   - name: listener-443
>     nodePort: 31294
>     port: 443
>     protocol: TCP
>     **_targetPort: 443_**
>   selector:
>     app.kubernetes.io/instance: abc-gateway
>     app.kubernetes.io/name: abc-gateway
>     gateway.networking.k8s.io/gateway-name: abc-gateway
>   sessionAffinity: None
>   type: LoadBalancer
> status:
>   loadBalancer:
>     ingress:
>     - ip: xxx.xxx.xxx.xxx
>       ipMode: VIP

**Comment by davidjumani** [comment]
Hi @binoysankar, I tried to reproduce this locally with jaeger and grafana. The traces are showing up correctly.
Could you please try to verify this with a local otel stack. Ref: https://kgateway.dev/docs/main/observability/otel-stack/

<img width="855" height="723" alt="Image" src="https://github.com/user-attachments/assets/e173894e-1ce0-4a10-804a-b74a22f3211b" />

**Comment by binoysankar** [comment]
Hi @davidjumani 
Sorry for the delayed response. I have tested with the latest version ```v2.2.0-beta.1``` of KGateway and the above mentioned issue is resolved. I am closing this ticket.

Thank you for your support.

**Comment by tolik93** [comment]
@binoysankar just a question about the implementation of datadog apm with kgateway. Is it possible to share your configuration and the listenerpolicies? I use datadog and kgateway in AWS EKS cluster and still can't make it working. It would be great if you share your knowledge. Thank you in advice

**Comment by binoysankar** [comment]
> [@binoysankar](https://github.com/binoysankar) just a question about the implementation of datadog apm with kgateway. Is it possible to share your configuration and the listenerpolicies? I use datadog and kgateway in AWS EKS cluster and still can't make it working. It would be great if you share your knowledge. Thank you in advice

Hi @tolik93, For me prior to kgateway 2.2 below is the configuration which worked for me in datadog.

```
kubectl apply -f - <<EOF
apiVersion: gateway.kgateway.dev/v1alpha1
kind: HTTPListenerPolicy
metadata:
  name: tracing-policy
  namespace: kgateway-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: xxx-gateway
  tracing:
    provider:
      openTelemetry:
        serviceName: "xxx-kgateway"
        resourceDetectors:
          - environmentResourceDetector: {}
        grpcService:
          backendRef:
            name: opentelemetry-collector
            namespace: otlp
            port: 4317
    spawnUpstreamSpan: true
    attributes:
      - name: "env"
        literal:
          value: "dev"
      - name: "geo"
        literal:
          value: "emea"
      - name: "region"
        literal:
          value: "westeurope"
EOF
```

There are some implementation change in 2.2 version where the above will be deprecated in later version AFAIK.

```
kubectl apply -f- <<EOF
apiVersion: gateway.kgateway.dev/v1alpha1
kind: ListenerPolicy
metadata:
  name: tracing-policy
  namespace: kgateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: xxx-gateway
  default:
    httpSettings:
      tracing:
        provider:
          openTelemetry:
            serviceName: "xxx-kgateway"
            resourceDetectors:
              - environmentResourceDetector: {}
            grpcService:
              backendRef:
                name: opentelemetry-collector
                namespace: otlp
                port: 4317
        spawnUpstreamSpan: true
        attributes:
          - name: env
            literal:
              value: "dev"
          - name: geo
            literal:
              value: "emea"
          - name: region
            literal:
              value: "westeurope"
    perConnectionBufferLimitBytes: 1024
EOF
```
